# Generated by Django 2.2.1 on 2019-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_total', models.CharField(max_length=30)),
                ('header_revenue', models.CharField(max_length=30)),
                ('header_growth', models.CharField(max_length=30)),
                ('right_bon', models.CharField(max_length=30)),
                ('right_cards', models.CharField(max_length=30)),
                ('right_discounts', models.CharField(max_length=30)),
                ('right_stock', models.CharField(max_length=30)),
                ('right_cards_sold', models.CharField(max_length=30)),
                ('right_bon_sold', models.CharField(max_length=30)),
                ('right_cards_in_stock', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
